# Generated by Django 4.1.7 on 2023-02-23 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=models.CharField(blank=True, help_text='Content', max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ro',
            field=models.CharField(blank=True, help_text='Content', max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='short_description_en',
            field=models.CharField(blank=True, help_text='Short description', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='short_description_ro',
            field=models.CharField(blank=True, help_text='Short description', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(help_text='News title', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ro',
            field=models.CharField(help_text='News title', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.CharField(blank=True, help_text='Content', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Published date'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description',
            field=models.CharField(blank=True, help_text='Short description', max_length=256, null=True),
        ),
    ]
