# Generated by Django 4.1.7 on 2023-03-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_hepoi_eoi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eoi',
            name='hepoi',
        ),
        migrations.AddField(
            model_name='eoi',
            name='hepoi',
            field=models.ManyToManyField(help_text='programm of interest', to='pages.hepoi'),
        ),
    ]
