# Generated by Django 4.1.7 on 2023-03-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_eoi_hepoi_eoi_hepoi'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='News title', max_length=64)),
                ('title_en', models.CharField(help_text='News title', max_length=64, null=True)),
                ('title_ro', models.CharField(help_text='News title', max_length=64, null=True)),
                ('url', models.URLField(help_text='URL address of the page', unique=True)),
                ('content', models.TextField(blank=True, help_text='Content', null=True)),
                ('content_en', models.TextField(blank=True, help_text='Content', null=True)),
                ('content_ro', models.TextField(blank=True, help_text='Content', null=True)),
            ],
        ),
    ]
