# Generated by Django 4.1.7 on 2023-03-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_rename_url_generalpage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(default='dsadsa', help_text='URL address of the news detail page', unique=True),
            preserve_default=False,
        ),
    ]
