# Generated by Django 4.1.7 on 2023-03-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_news_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('name', models.CharField(help_text='File name', max_length=64)),
                ('slug', models.SlugField(help_text='URL address of the file', unique=True)),
            ],
        ),
    ]
