# Generated by Django 4.1.7 on 2023-03-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_events_alter_filestorage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='content_en',
            field=models.CharField(blank=True, help_text='Content', max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='content_ro',
            field=models.CharField(blank=True, help_text='Content', max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='short_description_en',
            field=models.CharField(blank=True, help_text='Short description', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='short_description_ro',
            field=models.CharField(blank=True, help_text='Short description', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='title_en',
            field=models.CharField(help_text='News title', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='title_ro',
            field=models.CharField(help_text='News title', max_length=64, null=True),
        ),
    ]
